### ISSUE TITLE
Trail/Park Naming.

### ISSUE THREAD

**Issue by EricMentele** [EricMentele/Seattle-Trails#22]
I'd like to come up with a naming convention for dealing with dictionary keys/trail names. Does a trail have paths(Trail Objects with the same name)? Maybe a park has trails? Topic for discussion.

**Comment by TAhub** [comment]
Well, at the moment we are storing trails as a dictionary of parks, each of which contain one or more trails. I think it'd be reasonable to just call them parks, and a park contains multiple trails.

**Comment by EricMentele** [comment]
Cool sounds good to me.
