### ISSUE TITLE
Schedule Mob Programming Code Review Session

### ISSUE THREAD

**Issue by EricMentele** [EricMentele/Seattle-Trails#23]
I think it would be cool, while our project is small, to do a mass screen share and talk about code organization, naming, style, documentation etc. I've been doing refactoring and I want to make sure I'm not offending anyone and we are on the same page as expectations.

It is easy for a project to become unreadable and disorganized when everyone is writing in their own style. [It can also fall apart.](https://www.youtube.com/watch?v=BbgOzPzdRVw)

**Comment by TAhub** [comment]
I'm open all next week. I'd prefer mornings.

**Comment by EricMentele** [comment]
Google Hangout scheduled for Thursday the 14th at 6pm.
