### ISSUE TITLE
Volunteering form

### ISSUE THREAD

**Issue by TAhub** [EricMentele/Seattle-Trails#39]

**Comment by TAhub** [comment]
We need a form for volunteering your work. Ideally it should use some refactored classes, to re-use code from the social tab.

**Comment by EricMentele** [comment]
@TAhub I made this an email view fired by a temporary button; however, now I am thinking about doing a web view with the link @chukundi sent us to sign up for volunteering.

**Comment by TAhub** [comment]
That sounds reasonable, yeah. The form doesn't seem to have many parks-related assignments though, so it might be confusing to the user for the trails app to send them to a form where like 75% of the options are community center coaches.

**Comment by chukundi** [comment]
Yes I have a separate, finite form that I use. I can send when I get to my computer

Sent from my iPhone

On Apr 13, 2016, at 9:31 AM, Theodore Abshire <notifications@github.com<mailto:notifications@github.com>> wrote:

That sounds reasonable, yeah. The form doesn't seem to have many parks-related assignments though, so it might be confusing to the user for the trails app to send them to a form where like 75% of the options are community center coaches.

##

**Comment by EricMentele** [comment]
@chukundi I see. So I will have a pre-formatted email based on the form, sent to the email address you designate. That sound good?
